### ISSUE TITLE
Não compila, apresenta vários bugs

### ISSUE THREAD

**Issue by gabrielpotumati** [pagarme/pagarme-net-standard-sdk#30]
![image](https://user-images.githubusercontent.com/7015404/223542818-82526d0d-7eab-444d-884c-aee5dc5eacb0.png)

**Comment by magnomoreira** [comment]
Boa tarde @gabrielpotumati, tudo bem ?
Infelizmente o código do repositório esta com alguns problemas que já estamos resolvendo. 
Caso queira utiliza-lo, faça sua instalação via gerenciador de pacote, segue o link do mesmo: [](https://www.nuget.org/packages/Pagar.me.NetStandard/6.3.0)
